### ISSUE TITLE
0.37.2 regression: a warm .jac/cache serves stripped module interfaces (E1030 on declared fields)

### ISSUE THREAD

**Issue by MalithaPrabhashana** [jaseci-labs/jac#8909]
### Root cause

The always-on JIR analysis cache added by #8836 (commit `3d180d82d`, "Always-on
JIR analysis cache: module interfaces, dependency cutoff, diagnostics replay")
landed between v0.37.1 and v0.37.2. Once a run has populated `.jac/cache`, a
later compile can read back a module interface that is missing its members. The
checker then reports declared fields as absent (E1030) and stops recognising
archetypes as nodes (E1096/E1097/E1098).

The state is on disk, so it outlives the process: a run of one command poisons
an unrelated later run of a different command. Deleting `.jac/cache` restores
correct behaviour immediately.

### Minimal reproduction: three files

Compiling **two** test files that have nothing to do with the affected type is
enough. Afterwards a third file, compiled on its own, fails.

jac 0.37.3 release asset, macOS arm64, `JAC_TEST_JOBS=1`, tree is
`jaseci-labs/jacBuilder` at branch `migrate/jac-0.37`.

```
$ rm -rf .jac/cache
$ jac test tests/jachammer/sandbox_factory_test.jac
76 passed in 49.49s

$ rm -rf .jac/cache
$ jac test tests/jachammer/reconciler_lifecycle_test.jac \
           tests/jachammer/resume_and_sandbox_select_test.jac
7 passed in 116.63s

$ jac test tests/jachammer/sandbox_factory_test.jac
1 error in 10.74s
```

The third command is byte for byte the first. Same binary, same file, same tree.
The only thing that changed is what the second command left in `.jac/cache`.
Note the timing too: 10.74s against 49.49s, so it is taking the cached path and
returning a wrong answer quickly.

The error lands in a library module, not in the test that was named:

```
jaclang.meta_importer.JacSourceCompileError: sandbox/providers/kubernetes_sandbox.jac failed to compile:
error[E1030]: Type "SandboxConfig" has no attribute "k8s_client_refresh_seconds"
  --> sandbox/providers/kubernetes_sandbox.jac:204:37
  204 |         refresh_after = self.config.k8s_client_refresh_seconds;
      |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E1030]: Type "SandboxConfig" has no attribute "ttl_seconds"
  --> sandbox/providers/kubernetes_sandbox.jac:290:36
  290 |         return max(int(self.config.ttl_seconds) + 3600, 7200);
      |                                    ^^^^^^^^^^^
error[E1030]: Type "SandboxConfig" has no attribute "namespace"
  --> sandbox/providers/kubernetes_sandbox.jac:370:37
  370 |             namespace = self.config.namespace;
      |                                     ^^^^^^^^^
```

`SandboxConfig` declares all three, and neither of the two poisoning files
imports or mentions `SandboxConfig` anywhere.

`rm -rf .jac/cache` and the same command is back to `76 passed`.

### It is deterministic

8 out of 8 trials reproduced, each trial being: clear the cache, compile the
poisoning set, then run the target file alone and look for E1030.

```
2-file pair, 5 trials      FAIL FAIL FAIL FAIL FAIL
16-file batch, 3 trials    FAIL FAIL FAIL
```

### Minimisation

Starting from a 16 file batch and shrinking, checking after each step whether
the target file still fails when run alone: 15 partners -> 8 -> 4, and at that
point four different **pairs** each reproduce it:

```
reconciler_lifecycle_test.jac + resume_and_sandbox_select_test.jac
reconciler_lifecycle_test.jac + resync_preview_test.jac
resume_and_sandbox_select_test.jac + resync_preview_test.jac
resume_and_sandbox_select_test.jac + runtime_env_test.jac
```

No single file poisons on its own, so two modules have to be compiled in the
same run for it to happen.

### Same 30 files, 0.37.1 against 0.37.3

Cold cache both times:

```
0.37.1    408 passed
0.37.3    265 passed, 8 error
```

The 8 are spread over unrelated files and types, so this is not one bad model:

```
error[E1030]: Type "CliDeviceRequest" has no attribute "status"
error[E1030]: Type "CliDeviceRequest" has no attribute "created_at"
error[E1030]: Type "DeployJob" has no attribute "status"
error[E1030]: Type "Project" has no attribute "name"
error[E1030]: Type "SandboxConfig" has no attribute "cpu_limit"
error[E1030]: Type "SandboxConfig" has no attribute "base_image"
```

### What did not reproduce it

Two synthetic projects on 0.37.3, both clean cold and warm, so the trigger is
not simply compiling several modules together:

1. 40 test files importing one shared module holding an `obj` and a `node`.
   80 passed cold, still correct warm.
2. 20 test files importing the model directly and through 15 intermediate
   modules that also import it, to force a diamond. 40 passed, still correct
   warm.

So something about the real tree matters. It is a `[scale.microservices]`
project with `[placement.pins]`, so a client/server placement split is the
obvious difference to look at first.

### Version boundary

v0.37.1 to v0.37.2 is 13 commits, and `3d180d82d` is the only one touching
interface caching. v0.37.1 has no such cache and is clean on every case above,
including the exact 3 file repro. `a662f17b4` (#8886) is an ancestor of v0.37.3
and does not fix it.

### Probably the same defect as #8889

#8889 reports the same cache handing back a degraded interface, on the codegen
side rather than the checker side: "On a warm analysis cache, a client module
that imports a server function can be emitted with the function's parameters
missing." Same cache, same class of loss, different consumer.

#8828 is a similar symptom in the check lane, but it is in-process and goes
green on rerun. This one is on disk and sticky: a plain rerun stays red, and
`rm -rf .jac/cache` is what clears it.

### Impact

No usable workaround. Clearing the cache fixes the next run, but any run that
compiles a couple of modules can poison it again, so CI cannot rely on it. We
are pinned to 0.37.1.

### Other shapes seen

`node SandboxInstance` (`shared/models.jac:187`) from
`sandbox_project_edge_test.jac` and `sandbox_cross_user_isolation_test.jac`, and
`PushSubscription` / `UserProfile` from `push_notifier_test.jac`, where the
connection operators reject the node too:

```
error[E1030]: Type "PushSubscription" has no attribute "endpoint"
error[E1097]: Connection right operand must be a node instance
error[E1096]: Connection left operand must be a node instance
error[E1098]: Connection type must be an edge instance
```

The title originally said "node archetypes". The archetype kind is irrelevant,
plain `obj` declarations such as `SandboxResult` and `SandboxConfig` are hit
identically. Adding `[placement.pins]` appeared to help for the same reason it
misled us elsewhere: it changes what gets compiled, and so what lands in the
cache.

### Environment

macOS arm64 and Linux x86_64 CI, release assets `jac-0.37.1`, `jac-0.37.2`,
`jac-0.37.3`, `JAC_TEST_JOBS=1`. The repro tree is private; happy to grant
access, or to cut down a shareable tree if that is easier.

**Comment by MalithaPrabhashana** [comment]
### Still reproduces on 0.37.3, and here is a cleaner single-file case

Re-measured against the release published today. 0.37.3 contains a662f17b4
(#8886, "jac check . stops failing order-dependently on files it never
touched"), which looked like it might be this. It is not: the same failure is
there.

A better reproducer than the one in the original report, which needed a
16-file batch. One file, one command, in jacBuilder:

```
jac test tests/jachammer/sandbox_factory_test.jac
```

```
  0.37.1    76 passed
  0.37.2     1 error
  0.37.3     1 error
```

The error:

```
error[E1030]: Type "SandboxResult" has no attribute "sandbox_id"
  --> tests/jachammer/sandbox_factory_test.jac:563:18
   563 |     sid = result.sandbox_id;

error[E1053]: Cannot assign <Unknown> to parameter 'sandbox_id' of type str
  --> tests/jachammer/sandbox_factory_test.jac:565:39
```

`sandbox_id` is the second field on the type, in
`sandbox/abstractions/models/sandbox_result.jac`:

```jac
obj SandboxResult {
    has success: bool,
        sandbox_id: str = "",
        url: str = "",
        ...
}
```

So an `obj` imported from another module loses its declared fields, the same way
the `node` archetypes in the original report did. Whatever this is, it is not
specific to node archetypes.

One correction to the original report while I am here. It named
`tests/jachammer/sandbox_project_edge_test.jac`, and that file no longer
reproduces on any of the three versions. The failure moves with what else is
compiled and with unrelated changes elsewhere in the tree, which is worth knowing
if someone tries to bisect it: a case that stops reproducing is not evidence the
bug is gone. `sandbox_factory_test.jac` above is reproducing consistently for me
right now, on both affected releases.

We remain pinned to 0.37.1 because of this.

**Comment by MalithaPrabhashana** [comment]
> **Superseded.** The minimisation and the "scales with file count" claim in this
> comment are wrong, see the correction below and the rewritten issue body. There
> is a three file repro. The cold cache versus warm cache result below still holds.

Root cause found, and the issue body has been rewritten around it. The short
version for anyone who read the original:

It is not the checker and it is not placement. It is the on-disk JIR analysis
cache from #8836 (`3d180d82d`). A warm `.jac/cache` returns module interfaces
with their members missing.

Same 0.37.3 binary, same file, same tree, only the cache differs:

```
rm -rf .jac/cache && jac test sandbox_factory_test.jac   ->  76 passed
jac test <30 other files> sandbox_factory_test.jac       ->   8 error
jac test sandbox_factory_test.jac                        ->   1 error
rm -rf .jac/cache && jac test sandbox_factory_test.jac   ->  76 passed
```

The third line is the point: the file compiles alone and fails, with the binary
that passed it two lines earlier. The poison outlives the process and is only
cleared by deleting the directory. Failure count also scales with how many files
the poisoning run compiled (15 files gives 1 error, 30 gives 8), and no single
partner file reproduces it, so it looks like a capacity or cutoff behaviour
rather than one interface being serialised wrongly.

This also explains why the earlier repros in this thread looked unstable and why
`[placement.pins]` appeared to help: both were really changing what got compiled
and therefore what landed in the cache.

I also retitled it. The original said "node archetypes", but plain `obj`
declarations are hit identically, so the archetype kind was a red herring.

#8889 looks like the same defect seen from codegen rather than the checker: a
warm analysis cache there emits a client stub with the function's parameters
missing. Worth fixing as one thing.

**Comment by MalithaPrabhashana** [comment]
Correcting two things I posted in the comment above, and the issue body has been
rewritten around the corrected results.

**There is a three file repro.** I said earlier that no minimal culprit existed
and that only the full set reproduced it. That was wrong, and it came from a
broken test harness on my side (unquoted parameter expansion in zsh, which does
not word split, so several "batch" runs silently passed one bogus filename and
did nothing). Redone properly, minimisation goes 15 partners -> 8 -> 4, and four
different **pairs** each reproduce it. Compiling two unrelated test files is
enough to make a third file fail when it is later compiled on its own.

**I also overstated the mechanism.** I said the failure count scales with how
many files are compiled. Two synthetic projects, 40 files sharing a module and
20 files reaching a module through 15 intermediates, do not reproduce it at all
on 0.37.3. So it is not simply volume, and something about the real tree is
required. Both negative results are in the body now.

What did hold up, and is re-verified 8 out of 8 trials: cold cache passes, warm
cache fails, same binary and same command, and the poisoned state persists on
disk across processes until `.jac/cache` is deleted.

Worth noting for whoever picks this up: in the three file repro the error does
not land in the test file that was named. It lands in a library module, on a
type that neither poisoning file mentions.

**Comment by marsninja** [comment]
Fixed by #8966, merged 2026-09-04 and first shipped in v0.37.5 (released 2026-09-06).

The poisoned entry was never the leaf module's interface. It was the importer's: the interned `ClassDetailsShared` for an imported class kept pointing at a tree the hub had already replaced, so once that tree was collected the writer could not place the class, recorded it as LOCAL with no scope, and the reader turned that into a member-less class. The leaf's digest never changed, so the dependency check kept serving the entry. That is why it was on disk, sticky, order-dependent, and invisible on small synthetic trees.

What changed: the intern follows the live tree, every hub install goes through one seam, and an interface with a class it cannot place is refused at persist (counted as `iface_incoherent`) rather than written. A future regression here is a cache miss, not a wrong answer.

The PR validated against the jacBuilder tree with your three-command sequence: cold run, two-file poisoning run, then `sandbox_factory_test.jac` alone gives 76 passed where it failed with E1030. Regression tests live in `jac/tests/compiler/test_iface_cache.jac` ("a class shared follows the tree the program holds for its module", "an interface that cannot place a class is not persisted", "a cross-reference into a stub is answered by the catalog"); the file passes on main today.

#8889 is the codegen-side report and stays open on its own.
